[versions]
agp = "8.7.3"
appcompat = "1.7.1"
annotation = "1.9.1"
core-ktx = "1.10.1"
material = "1.11.0"
guava = "33.4.0-android"
markwon = "4.6.2"
hiddenapibypass = "6.1"
window = "1.3.0"
commons_io = "2.5"
desugar = "2.1.5"
junit = "4.13.2"
test_ext_junit = "1.1.3"
espresso = "3.4.0"
drawerlayout = "1.2.0"
preference = "1.2.1"
viewpager = "1.1.0"
robolectric = "4.16"
termux_am = "2.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
com-google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
com-google-guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
markwon-ext-strikethrough = { group = "io.noties.markwon", name = "ext-strikethrough", version.ref = "markwon" }
markwon-linkify = { group = "io.noties.markwon", name = "linkify", version.ref = "markwon" }
markwon-recycler = { group = "io.noties.markwon", name = "recycler", version.ref = "markwon" }

org-lsposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons_io" }
com-android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test_ext_junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-viewpager = { group = "androidx.viewpager", name = "viewpager", version.ref = "viewpager" }

org-robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
termux-am-library = { group = "com.termux", name = "termux-am-library", version.ref = "termux_am" }